### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by sjf18** [wangch-g/lanet#1]
Hi,
thanks for your great work, do u have any plan to release the training code?

**Comment by wangch-g** [comment]
> 
We are organizing the training code and will release it soon.

**Comment by cxmscb** [comment]
> > 
> 
> We are organizing the training code and will release it soon.

Hope it soon.

**Comment by cxmscb** [comment]
Thanks for uploading training codes. Could the training code be used for training models?
