### ISSUE TITLE
Why is the shuffle config True in training?

### ISSUE THREAD

**Issue by cxmscb** [wangch-g/lanet#5]
Thanks for the sharing. I am confused about the the shuffle config in training.

`traindata_arg.add_argument('--shuffle', type=str2bool, default=False,
                            help='Whether to shuffle the train and valid indices')`

**Comment by wangch-g** [comment]
Thanks for pointing out, this code is released on the basis of the testing version. As for training, the shuffle config should be set as 'True'.

**Comment by cxmscb** [comment]
Thanks.
