### ISSUE TITLE
网络的推理延迟是多少？

### ISSUE THREAD

**Issue by JiangWeiHn** [wangch-g/lanet#8]
请问网络的推理速度怎么样？有没有在同一计算平台和其他的网络进行比较？我要用在机器人的slam上，所以比较关注延迟，在论文中没有找到。

**Comment by wangch-g** [comment]
推理速度没有专门测试过。V0版本的网络本身比较浅，而且也没有涉及到非常复杂的操作，如果需要的话可以尝试一下V0。

**Comment by JiangWeiHn** [comment]
好的 ，谢谢回答
