### ISSUE TITLE
论文的精度问题询问

### ISSUE THREAD

**Issue by Penge666** [wangch-g/lanet#9]
您好，拜读了您的LANet模型，太厉害了。现在尝试复现这篇文章，目前有个问题想向你请教一下，就是我在单2080ti卡运行net_work_v0的模型12epoch的指标和原论文的指标有点差异QAQ
![image](https://github.com/wangch-g/lanet/assets/54142179/a909b47f-26ff-4273-ba27-66da69f8d961)
![image](https://github.com/wangch-g/lanet/assets/54142179/6e31b834-c086-4250-b408-4e7a1f8c3a39)
想问一下这是为什么呢？感谢

**Comment by wangch-g** [comment]
您好！是重新训练的模型吗？
建议每一个epoch结束都保存一下model，最好的结果可能不在最后一个epoch。

**Comment by Penge666** [comment]
好的，谢谢你的回答，我再尝试尝试

**Comment by Penge666** [comment]
> 您好！是重新训练的模型吗？ 建议每一个epoch结束都保存一下model，最好的结果可能不在最后一个epoch。

作者您好，不好意思打扰你。我根据您文件夹中的net_work_v1模型跑了训练，但是在测试阶段遇到了如下的报错。调试中未找到错误的原因。
![image](https://github.com/wangch-g/lanet/assets/54142179/a9df035f-c612-4926-8565-2d8af304077c)
请问一下这是为什么呢？谢谢

**Comment by wangch-g** [comment]
这个是在测试过程中到某一张图像时出现的问题吧，你可以把遇到问题的那张图以及对应的输出可视化一下找找问题。
v1的训练损失函数有一些改动，这部分代码没有整理上来，直接训练的话在HPatch上结果大概率不如v0，我们训练的模型在其他问题下能找到下载链接，可以试一试。

**Comment by Penge666** [comment]
好的，我看看。感谢

**Comment by Penge666** [comment]
作者，您好，我在模型中有点地方看的不是很懂，能否留个联系邮箱啥的请教下呢？十分感谢

**Comment by Penge666** [comment]
作者，您好。请问下有评估MMA的代码吗？想参考下，十分感谢

**Comment by wangch-g** [comment]
wangch@mail.nwpu.edu.cn

**Comment by Penge666** [comment]
> [wangch@mail.nwpu.edu.cn](mailto:wangch@mail.nwpu.edu.cn)

好的，感谢🌹

**Comment by Zhangyuhaoo** [comment]
您好。不好意思打扰您了，我想请教下您是在哪里对训练模型进行精度指标实验的呢，期待您的回复！

**Comment by wangch-g** [comment]
> 您好。不好意思打扰您了，我想请教下您是在哪里对训练模型进行精度指标实验的呢，期待您的回复！

您好~ 我没太明白您的意思，如果是测试的话，README里有evaluation的相关说明。
